defaults: &defaults
  app_id: 'ALE1S42DXP22IB044SW4NE5N15G0OJRADOG4ZVDZNUIA14EI'
  app_secret: 'X0FCN245D4AFQG1ZMCZUULT3MYDULCPAK1OUA53JQNBDX0Q1'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults